### PR TITLE
HTML Markup Update

### PR DESCRIPTION
**Pull request by simialbi**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   | partial
| Fixed issues  | none

I updated existing classes from bootstrap 3 to generate bootstrap 4 markup, marked [Collapse](https://github.com/simialbi/yii2-bootstrap4/blob/master/src/Collapse.php) as deprecated and created [Accordion](https://github.com/simialbi/yii2-bootstrap4/blob/master/src/Accordion.php) for this purpose. I added the new class [ButtonToolbar](https://github.com/simialbi/yii2-bootstrap4/blob/master/src/ButtonToolbar.php)

I even started to change tests, but still have to update `CollapseTest` (rename to `AccordionTest`), `NavTest`, `TabsTest` and `ToggleButtonGroupTest` and add a `ButtonToolbarTest`. There are maybe any better/more `ActiveForm` markup tests needed.

### CODE REVIEW

**Comment by samdark** [comment]
Let's have it merged. Thank you!

**Comment by cjtterabyte** [comment]
Hi @samdark, @simialbi to make merged of these changes against the 2.0 branch (yii 3.0) you have to prepare another pull request, you just do not have to modify either the composer.json or BootstrapPluginAsset.php, if you like I can prepare it, greetings.

**Comment by samdark** [comment]
Yes, please do.

**Comment by simialbi** [comment]
@samdark I already did (#33)

**Pull request merged**
