### PR TITLE
Fix tests after change in 2.0.44

### PR DESCRIPTION
**Pull request by bizley**
This fixes the tests after https://github.com/yiisoft/yii2/pull/19098 change.
Reported in #230

### CODE REVIEW

**Comment by samdark** [comment]
👍

**Comment by marcovtwout** [comment]
@bizley It's described as fixing tests, but if I read correctly it actually fixes code instead?

**Comment by bizley** [comment]
Well, by setting the property in the code it fixes the tests.

**Comment by marcovtwout** [comment]
Yes, but just to be clear, this changes the default value of this property compared to BaseHtml (https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseHtml.php#L103) from false to true. While it mainly fixes a regression, perhaps it should be noted as such in the changelog.

**Pull request merged**
