### PR TITLE
NavBar role="navigation" is unneceseary

### PR DESCRIPTION
**Pull request by Thoulah**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | https://github.com/yiisoft/yii2-bootstrap/issues/137

Also fixes one of the things meant in https://github.com/yiisoft/yii2-bootstrap4/issues/10

### CODE REVIEW

**Comment by machour** [comment]
Thank you for this PR. 

Travis seems to be failing on something unrelated and that was passing the test just fine.. I'm looking into it.

**Comment by Thoulah** [comment]
I was looking into those test as well. Seems to be ActiveField Radio related. Nothing I touched :)

**Comment by Thoulah** [comment]
Is that really necessary? This change should have been here already in the first place, as it is also in yiisoft/yii2-bootstrap since 2016. Exactly why I was complaining in https://github.com/yiisoft/yii2-bootstrap4/issues/10

**Comment by machour** [comment]
yii2-bootstrap & yii2-bootstrap4 are two separate packages :)

Since yii2-bootstrap4 have already been published, all enhancements / fixes that are done after that initial release should be mentioned in the change log, as usual.

**Comment by samdark** [comment]
Merged. Thank you!

**Pull request merged**
