### PR TITLE
Update composer.json branch 2.0.  - (#29).

### PR DESCRIPTION
**Pull request by cjtterabyte**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | #29 - update composer yii 3.0. branch 2.0.

### CODE REVIEW

**Comment by rob006** [comment]
Why did you removed support for 2.0?

**Comment by cjtterabyte** [comment]
@rob006 With all respect this branch is for the new version of yii, the main extensions in its version 3.0.x-dev have no support for 2.0, the master branch is the one that has support for 2.0, , if you check the main extensions that has been the action to take and of course missing in this extension, for example https://github.com/yiisoft/yii2-gii/blob/2.1/composer.json in its branch 2.1. does not have support for version 2.0, same happens in bootstrap4.

**Comment by rob006** [comment]
@cjtterabyte This is not really an answer. If this branch is able to work with both Yii 2.0 and 3.0 then there is no point of removing support for 2.0 "just because".

**Comment by cjtterabyte** [comment]
@rob006 This branch 2.0 was created only for yii 2.1. -> 3.0.

Add branch for Yii 2.1 #17

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
