### PR TITLE
FEATURE Bootstrap Collapse support #187

### PR DESCRIPTION
**Pull request by dshiryaev-plesk**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | 
| Fixed issues  | #187

### CODE REVIEW

**Comment by simialbi** [comment]
Why? It exists:
https://github.com/yiisoft/yii2-bootstrap4/blob/master/src/Accordion.php

**Comment by schmunk42** [comment]
> Why? It exists:
> https://github.com/yiisoft/yii2-bootstrap4/blob/master/src/Accordion.php

I think a Collapse is for a single panel, while an accordion is for multiple?
https://getbootstrap.com/docs/4.3/components/collapse/#example

**Comment by simialbi** [comment]
According the comment no:
https://github.com/yiisoft/yii2-bootstrap4/pull/188/files#diff-d26b3b1cb47b86484c8db442084dd915R14

**Comment by samdark** [comment]
Oh :)

Thanks, @simialbi :)

And thank you, @dshiryaev-plesk for the pull request.

**Comment by dshiryaev-plesk** [comment]
Thanks for the explanation.

**Comment by dshiryaev-plesk** [comment]
The Accordion class name is confusing because there is no Accordion component in Bootstrap 4: https://getbootstrap.com/docs/4.4/components/collapse.

**Comment by simialbi** [comment]
Yeah what you link here is not the accordion. It's the collapse, it's used in many ways as in bootstrap. The accordion itself is called accordion in bootstrap too:
https://getbootstrap.com/docs/4.4/components/collapse/#accordion-example

**Pull request closed without merging**
