### PR TITLE
fix checkbox&radio error class

### PR DESCRIPTION
**Pull request by alexgivi**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | #173

### CODE REVIEW

**Comment by alexgivi** [comment]
not sure, that it's working variant. tests were failed before fix, and no changes after. There are no validation tests.

**Comment by simialbi** [comment]
I miss a test there

**Comment by samdark** [comment]
Is it solved by https://github.com/yiisoft/yii2-bootstrap4/commit/d1af1e2db4481a3ae523a35a6b5cb0b30a56f13b?

**Comment by alexgivi** [comment]
> Is it solved by [d1af1e2](https://github.com/yiisoft/yii2-bootstrap4/commit/d1af1e2db4481a3ae523a35a6b5cb0b30a56f13b)?

i think yes

**Comment by bizley** [comment]
Closed in favor of https://github.com/yiisoft/yii2-bootstrap4/pull/208

**Pull request closed without merging**
