### PR TITLE
Fixes issue #181

### PR DESCRIPTION
**Pull request by marcovtwout**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | #181

### CODE REVIEW

**Comment by WinterSilence** [comment]
[step forward](https://github.com/yiisoft/yii2/pull/18653#issue-643690343)

**Comment by bizley** [comment]
Yes, @marcovtwout could you refactor it to use the new parent's method?

**Comment by marcovtwout** [comment]
@bizley PR updated, but I assume tests will fail until yiisoft/yii gets the next stable release.

**Comment by bizley** [comment]
Yes, not a problem, we will wait. Thank you.

**Review by bizley — APPROVED** [review]

**Comment by samdark** [comment]
> I assume tests will fail until yiisoft/yii gets the next stable release.

Then we need to bump minimal version in composer.json before release.

**Comment by WinterSilence** [comment]
@marcovtwout possible error - `yii\bootstrap4\ToggleButtonGroup::$name` is empty (i checked chain `yii\widgets\InputWidget::init()` - `yii\bootstrap4\ToggleButtonGroup::init()`)

**Comment by marcovtwout** [comment]
@WinterSilence I don't think that is correct - all input widgets require either model+attribute or name to be set: https://github.com/yiisoft/yii2/blob/master/framework/widgets/InputWidget.php#L74-L76 - so `name` should always be available.

**Comment by WinterSilence** [comment]
@marcovtwout https://github.com/yiisoft/yii2-bootstrap4/blob/37a0cc2f11f6f38b562ab9306eed2f899b72838a/src/ToggleButtonGroup.php#L72 parent method called BEFORE you pass config

**Comment by WinterSilence** [comment]
@marcovtwout you right, my fail config loaded before `init()`

**Review by samdark — APPROVED** [review]
Let's add CHANGELOG and merge it.

**Comment by marcovtwout** [comment]
Updated Changelog and composer.json. Note that yii2 2.0.43 is not release yet, I suggest to rerun tests and merge this PR after 2.0.43 is released.

**Comment by marcovtwout** [comment]
@samdark Could you trigger the build again to see if it now passes? If it passes, it can be merged.

**Comment by samdark** [comment]
Done. Failed.

**Comment by marcovtwout** [comment]
@samdark The failed CI is unrelated to this PR, see https://github.com/yiisoft/yii2-bootstrap4/issues/230

**Comment by bizley** [comment]
👍🏻

**Pull request merged**
