### PR TITLE
Change Bower to NPM & update composer.json.

### PR DESCRIPTION
**Pull request by snickom**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #84

### CODE REVIEW

**Comment by samdark** [comment]
Looks good to me but can't test with real app this time. Some battlefield testing, anyone?

**Comment by samdark** [comment]
@simialbi what kind of problems?

**Comment by simialbi** [comment]
E.g. not functional / installabe packages, broken dependencies etc.
Not installable packages appears sporadically.

**Comment by samdark** [comment]
That is quite weird for a package and a package manager that is used widely.

**Comment by simialbi** [comment]
Yes it is. I don't know if it just happens in combination with https://asset-packagist.org. I never tried without it.
There is still some other reason why not to use NPM. E.g.:
https://thehackernews.com/2018/11/nodejs-event-stream-module.html

**Comment by snickom** [comment]
Sometimes, you have to manually click on the detail of the package (or click on fetch) on https://asset-packagist.org/ to download the latest version of the package. It's a shame they do not do it periodically with cron. But you can use foxy/foxy as yarn bridge.

**Comment by samdark** [comment]
@snickom I think they do fetch it. asset-packagist was created by @hiqsol and @SilverFire btw.

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
