### PR TITLE
update yii2 dependency to 2.1.x-dev

### PR DESCRIPTION
**Pull request by albertborsos**
because this repository is only compatible with Yii 2.1

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | yes
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by Thoulah** [comment]
I'm using this with 2.0.15.1...

**Comment by albertborsos** [comment]
@Thoulah based on this https://github.com/yiisoft/yii2-bootstrap/issues/77#issuecomment-369005748 this extension will be compatible only with Yii 2.1

**Comment by rob006** [comment]
@albertborsos This was only a suggestion, not a decision.

**Comment by samdark** [comment]
Please rebase against 2.0 branch. Thanks.

**Pull request closed without merging**
