### PR TITLE
Breadcrumb widget

### PR DESCRIPTION
**Pull request by onmotion**
based on yii\widgets\Breadcrumbs

| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | 
| Fixed issues  |

### CODE REVIEW

**Comment by simialbi** [comment]
I'm not sure if this is really necessary.
You can achieve the same result like this:
```php
use yii\widgets\Breadcrumbs;

echo Breadcrumbs::widget([
    'links' => [...],
    'tag' => 'ol',
    'itemTemplate' => '<li class="breadcrumb-item">{link}</li>',
    'activeItemTemplate' => '<li class="breadcrumb-item active" aria-current="page">{link}</li>',
    'options' => [
        'class' => 'breadcrumb'
    ]
]);
```

**Comment by onmotion** [comment]
> I'm not sure if this is really necessary.
> You can achieve the same result like this:
> 

Yes, but it's for BS4 explicitly. It's convenient for migrating from BS3 with Yii2. Of course all people can do everything themselves :)

**Comment by samdark** [comment]
I think it's convenient to have it. @omnilight how about covering it with unit tests?

**Comment by onmotion** [comment]
@samdark на выходных сделаю.

**Comment by samdark** [comment]
@onmotion seems @simialbi was faster...

**Pull request closed without merging**
